#!/bin/sh
#
# Copyright (c) 2015, Linaro Limited
# All rights reserved.
#
# SPDX-License-Identifier:	BSD-3-Clause
#

# directories where pktio_main binary can be found:
# -in the validation dir when running make check (intree or out of tree)
# -in the script directory, when running after 'make install', or
# -in the validation when running standalone (./pktio_run) intree.
# -in the current directory.
# running stand alone out of tree requires setting PATH
PATH=$(pwd)/pktio:$PATH

pktio_path=$(which pktio${EXEEXT})
if [ -x "$pktio_path" ] ; then
	echo "running with pktio: $pktio_run_path"
else
	echo "cannot find pktio: please set you PATH for it."
fi

# directory where platform test sources are, including scripts
TEST_SRC_DIR=$(dirname $0)

# exit codes expected by automake for skipped tests
TEST_SKIPPED=77


run_test()
{
	local ret=0
	BOARD_TYPE=$(cat /mppa/board0/type)

	case "$BOARD_TYPE" in
		"ab01")
			IFLIST="loop e0:loop e1:loop e0p0:loop e1p1:loop cluster0:tags=100"
			;;
		"explorer")
			IFLIST="loop e1:loop e1p1:loop cluster0:tags=100"
			;;
		"")
			IFLIST="loop"
			;;
		*)
			IFLIST="loop"
			;;
	esac
	if [ "$RUN_TARGET" == "k1-cluster" ]; then
		IFLIST="loop"
	fi
	if [ "$ODP_PKTIO_IF0" != "" ]; then
		IFLIST=${ODP_PKTIO_IF0}
	fi

	for IF in ${IFLIST}; do
		${TARGET_RUNNER} $(which pktio${EXEEXT}) ${IF}
		if [ $? -ne 0 ]; then
			ret=1
		fi
	done

	if [ $ret -ne 0 ]; then
		echo "!!! FAILED !!!"
	fi

	exit $ret
}

run()
{
	run_test
}

case "$1" in
	setup)   ;;
	cleanup) ;;
	*)       run ;;
esac
