#!/bin/sh -xe

cd $(dirname $(readlink -f ${0}))

libtoolize --force --copy && \
aclocal && \
autoheader && \
automake --add-missing --include-deps --copy && \
autoconf

if [ $? -ne 0 ]; then
	echo "Automake/Autoconf returned with error."
	exit 1
fi

CC=k1-nodeos-gcc  CXX=k1-nodeos-g++  ./configure --srcdir=`pwd` --prefix=$(pwd)/build/ --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test --host=k1-nodeos
make -j4 install