#!/bin/sh -xe

cd $(dirname $(readlink -f ${0}))

libtoolize --force --copy && \
aclocal && \
autoheader && \
automake --add-missing --include-deps --copy && \
autoconf

if [ $? -ne 0 ]; then
	echo "Automake/Autoconf returned with error."
	exit 1
fi
