#ifndef COMMON_H
#define COMMON_H 

#define MAGIC_SCALL_ETH_INIT 0x600
#define MAGIC_SCALL_ETH_OPEN 0x601
#define MAGIC_SCALL_ETH_GETMAC 0x602
#define MAGIC_SCALL_ETH_RECV 0x603
#define MAGIC_SCALL_ETH_SEND 0x604
#define MAGIC_SCALL_ETH_PROM_SET 0x605
#define MAGIC_SCALL_ETH_PROM_GET 0x606

#endif /* COMMON_H */
