SRCDIR   := $(shell dirname $(MAKEFILE_LIST))
FIRMDIR  := $(shell basename $(SRCDIR))

ODP_INCDIR = $(TOP_SRCDIR)/platform/mppa/include
ODP_SRCDIR = $(TOP_SRCDIR)/platform/mppa/
_CFLAGS   = -I$(ODP_INCDIR)
HDRFILES  = $(ODP_INCDIR)/odp_rpc_internal.h
SRCFILES  = $(ODP_SRCDIR)/odp_rpc.c

include $(shell dirname $(SRCDIR))/Makefile

