ifndef SRCDIR
	   SRCDIR   := $(shell dirname $$(echo $(MAKEFILE_LIST) | awk '{ print $$NF}'))
endif

FIRMDIR  := $(shell basename $(SRCDIR))

ODP_INCDIR = $(TOP_SRCDIR)/platform/mppa/include
ODP_SRCDIR = $(TOP_SRCDIR)/platform/mppa/
_CFLAGS   += -I$(ODP_INCDIR) -I$(TOP_SRCDIR)/include
HDRFILES  +=
SRCFILES  +=

include $(shell dirname $(SRCDIR))/Makefile

